const main = {
    "title": "JavaScript Developer",
    "name": "Malyi M.G",
    "prof": "web-developer",
    "currentPosition": "Front-end (React JS)",
    "currentStatus": "Front-end (React JS)",
    "currentCompany": "Front-end (React JS)",
    "dateOfStart": "30-12-2016",
    "img": {
      "imgUrl": "/",
      "alt": "",
      "title": ""
    },
    "description": "",
    "skills": [
      {
        "name": "",
        "icon": "",
        "title": "",
        "perc": "",
        "level": 0,
        "documents": [],
        "links": {"linksCrs": [], "linksRes": [], "other": {}}
      },
    ],
    "links": [{"icon": "", "url": "", "title": ""}]
  },
  experienceListDates = [
    {
      date: "00-00-00",
      company: "",
      link: "/",
      current: false,
      startDate: "00-00-00",
      finishDate: "00-00-00",
      iconUrl: "",
      pops: false,
    },
    {
      date: "00-00-00",
      company: "",
      link: "/",
      current: false,
      startDate: "00-00-00",
      finishDate: "00-00-00",
      iconUrl: "",
      pops: false,
    },
    {
      date: "00-00-00",
      company: "",
      link: "/",
      current: false,
      startDate: "00-00-00",
      finishDate: "00-00-00",
      iconUrl: "",
      pops: false,
    },
    {
      date: "00-00-00",
      company: "",
      link: "/",
      current: false,
      startDate: "00-00-00",
      finishDate: "00-00-00",
      iconUrl: "",
      pops: false,
    },
    {
      date: "00-00-00",
      company: "",
      link: "/",
      current: false,
      startDate: "00-00-00",
      finishDate: "00-00-00",
      iconUrl: "",
      pops: false,
    },
  ],
  experience = [
    {
      id: "someCompany",
      title: "",
      position: "",
      desc: "",
      label: "/",
      chef: "",
      techStack: [
        {
          name: "",
          icon: "",
          title: "",
          state: "",
        },
      ],
      links: [
        {icon: "email", link: "", title: ""},
        {icon: "linkedIn", link: ""},
      ],
    },
  ],
  experienceForPops = [
    {
      id: "someCompany",
      title: "",
      position: "",
      label: "/",
      urlFull: "experience/someCompany",
    },
  ],
  lessons = [
    {
      id: 7777777,
      crsName: "JavaScriptAdvancedReact",
      subject: "",
      linkRepo: "https://beetroot.academy/en/courses/advanced-javascript/",
      reposList: ["/#task", "/#task2"],
      chatUrl: [],
    },
  ],
  hw = [
    {
      id: 55557777,
      lessonId: 7777777,
      subject: "",
      linkRepo: "https://beetroot.academy/en/courses/advanced-javascript/",
      reposList: ["/#task", "/#task2"],
      Comments: [],
    },
  ],
  courses = [
    {
      id: "beetroot",
      cont: {
        title: "Beetroot Academy",
        url: "beetroot/",
        link: "https://beetroot.academy/en/",
        listOfCourses: [
          {
            id: 1,
            iconLink: "/",
            title: "Front end",
            slug: "front-end",
            authorId: 1,
            category: "frontend",
            preview: "",
            finished: false,
            started: false,
            progress: 0,
            timeSpend: 0,
            timePlaned: 0,
            startDate: "00-00-00",
            finishDate: "00-00-00",
          },
          {
            id: 2,
            iconLink: "/",
            shortUrl: "JavaScriptAdvancedReact",
            title: "JavaScript Advanced React",
            slug: "javascript-advanced",
            authorId: 1,
            category: "frontend",
            preview: "",
            finished: true,
            started: false,
            progress: 0,
            timeSpend: 0,
            timePlaned: 0,
            startDate: "00-00-00",
            finishDate: "00-00-00",
          },
          {
            id: 3,
            iconLink: "/",
            title: "Backend PHP",
            slug: "backend-php",
            authorId: 2,
            category: "backend",
            preview: "",
            finished: false,
            started: false,
            progress: 0,
            timeSpend: 0,
            timePlaned: 0,
            startDate: "00-00-00",
            finishDate: "00-00-00",
          },
          {
            id: 4,
            iconLink: "/",
            title: "Python",
            slug: "python-course",
            authorId: 2,
            category: "backend",
            preview: "",
            finished: false,
            started: false,
            progress: 0,
            timeSpend: 0,
            timePlaned: 0,
            startDate: "00-00-00",
            finishDate: "00-00-00",
          },
          {
            id: 5,
            iconLink: "/",
            title: "Web Design",
            slug: "web-design",
            authorId: 3,
            category: "design",
            preview: "",
            finished: false,
            started: false,
            progress: 0,
            timeSpend: 0,
            timePlaned: 0,
            startDate: "00-00-00",
            finishDate: "00-00-00",
          },
          {
            id: 6,
            iconLink: "/",
            title: "Databases",
            slug: "databases",
            authorId: 2,
            category: "backend",
            preview: "",
            finished: false,
            started: false,
            progress: 0,
            timeSpend: 0,
            timePlaned: 0,
            startDate: "00-00-00",
            finishDate: "00-00-00",
          },
          {
            id: 7,
            iconLink: "/",
            title: "Clean Code",
            slug: "clean-code-humans",
            authorId: 2,
            category: "backend",
            preview: "",
            finished: false,
            started: false,
            progress: 0,
            timeSpend: 0,
            timePlaned: 0,
            startDate: "00-00-00",
            finishDate: "00-00-00",
          },
          {
            id: 8,
            iconLink: "/",
            title: "HTML 5",
            slug: "html-5",
            authorId: 1,
            category: "frontend",
            preview: "",
            finished: false,
            started: false,
            progress: 0,
            timeSpend: 0,
            timePlaned: 0,
            startDate: "00-00-00",
            finishDate: "00-00-00",
          },
          {
            id: 9,
            iconLink: "/",
            title: "Framework Laravel",
            slug: "framework-laravel",
            authorId: 2,
            category: "backend",
            preview: "",
            finished: false,
            started: false,
            progress: 0,
            timeSpend: 0,
            timePlaned: 0,
            startDate: "00-00-00",
            finishDate: "00-00-00",
          },
          {
            id: 10,
            iconLink: "/",
            title: "Framework Symphony",
            slug: "framework-symphony",
            authorId: 2,
            category: "backend",
            preview: "",
            finished: false,
            started: false,
            progress: 0,
            timeSpend: 0,
            timePlaned: 0,
            startDate: "00-00-00",
            finishDate: "00-00-00",
          },
        ],
        authors: [
          {id: 1, name: "Scott Alen"},
          {id: 2, name: "Robert Williams"},
          {id: 3, name: "Adam Clark"},
        ],
      },
    },
    {
      id: "itstep",
      cont: {
        title: "IT school 'Step'",
        list: [
          {
            id: 1,
            title: "Front end",
            slug: "front-end",
            authorId: 1,
            category: "frontend",
          },
          {
            id: 2,
            title: "JavaScript Advanced React",
            slug: "javascript-advanced",
            authorId: 1,
            category: "frontend",
          },
          {
            id: 3,
            title: "Backend PHP",
            slug: "backend-php",
            authorId: 2,
            category: "backend",
          },
          {
            id: 4,
            title: "Python",
            slug: "python-course",
            authorId: 2,
            category: "backend",
          },
          {
            id: 5,
            title: "Web Design",
            slug: "web-design",
            authorId: 3,
            category: "design",
          },
          {
            id: 6,
            title: "Databases",
            slug: "databases",
            authorId: 2,
            category: "backend",
          },
          {
            id: 7,
            title: "Clean Code",
            slug: "clean-code-humans",
            authorId: 2,
            category: "backend",
          },
          {
            id: 8,
            title: "HTML 5",
            slug: "html-5",
            authorId: 1,
            category: "frontend",
          },
          {
            id: 9,
            title: "Framework Laravel",
            slug: "framework-laravel",
            authorId: 2,
            category: "backend",
          },
          {
            id: 10,
            title: "Framework Symphony",
            slug: "framework-symphony",
            authorId: 2,
            category: "backend",
          },
        ],
        authors: [
          {id: 1, name: "Scott Alen"},
          {id: 2, name: "Robert Williams"},
          {id: 3, name: "Adam Clark"},
        ],
      },
    },
  ],
  seo = ""

module.exports = {
  main,
  courses,
  experience,
  seo,
  experienceListDates,
  experienceForPops,
  lessons,
  hw
}
